method: AE
data_corp: harvard

paths:
  data_train: "/rds/general/user/lrh24/home/thesis/Datasets/tuh-eeg-ab-clean/train"
  data_eval: "/rds/general/user/lrh24/home/thesis/Datasets/tuh-eeg-ab-clean/eval"
  data_harvard: "/rds/general/user/lrh24/ephemeral/harvard-eeg/EEG/bids_age_500_clean"
  results_root: "Results"

model:
  batch_size: 16
  num_epochs: 40
  dropout: 0.3
  weight_decay: 1e-4
  scheduler: cosine


reset: false