method: ctm
data_corp: harvard

paths:
  data_train: "/rds/general/user/lrh24/home/thesis/Datasets/tuh-eeg-ab-clean/train"
  data_eval: "/rds/general/user/lrh24/home/thesis/Datasets/tuh-eeg-ab-clean/eval"
  data_harvard: "/rds/general/user/lrh24/ephemeral/harvard-eeg/EEG/bids_2000_normal_abnormal_clean"
  results_root: "Results"

model:
  batch_size: 16
  num_epochs: 40
  dropout: 0.3
  weight_decay: 1e-4
  scheduler: cosine  # options: none | cosine | plateau

optuna:
  n_trials: 100
  val_split: 0.2
  patience: 20

reset: false